addReviewers: true

addAssignees: author

numberOfReviewers: 2

useReviewGroups: false

reviewers:
  - JeongminSung
  - yongsk0066
  - kimjeongwonn
  - saengmotmi
  - Yuddomack
  - DiveDiFF

useAssigneeGroups: false
