import { RUIColorThemeType } from './types';

/**
 * {@link https://www.figma.com/file/2qQ5eJPRTiAKyz6Q1IzfMJ/WEB?node-id=2570%3A12136&viewport=347%2C475%2C0.47}
 */
export const ruiColorTheme: RUIColorThemeType = {
  light: {
    '--rui-primary100': '#000000',
    '--rui-primary200': '#FFFFF9',
    '--rui-secondary100': '#FF5414',
    '--rui-contents000': '#212322',
    '--rui-contents100': '#61615F',
    '--rui-contents150': '#8B8B87',
    '--rui-contents200': '#B2B1AD',
    '--rui-contents300': '#CDCCC6',
    '--rui-contents999': '#FFFFF9',
    '--rui-disabled': '#CDCCC6',
    '--rui-disabled-role-red': '#FFAA8D',
    '--rui-disabled-secondary': '#FFCBBA',
    '--rui-role-red': '#BB3811',
    '--rui-role-yellow': '#EBA900',
    '--rui-role-blue': '#00B3EA',
    '--rui-role-green': '#29B31E',
    '--rui-bg100': '#FFFFFF',
    '--rui-bg200': '#F7F7F0',
    '--rui-bg300': '#E8E7E0',
    '--rui-bg-modal100': '#FFFFFF',
    '--rui-bg-modal200': '#F7F7F0',
    '--rui-bg-role-red': '#FCE9E6',
    '--rui-bg-secondary100': '#FFF2F0',
    '--rui-bg-highlight': '#FCF6E0',
    '--rui-bg-role-yellow': '#FCF6E0',
    '--rui-bg-role-blue': '#E0F5FC',
    '--rui-bg-role-green': '#E7F6E5',
    '--rui-white-fixed': '#FFFFF9',
    '--rui-black-fixed': '#000000',
    '--rui-divider': '#E8E7E0',
  },
  dark: {
    '--rui-primary100': 'hh',
    '--rui-primary200': 'hh',
    '--rui-secondary100': 'hh',
    '--rui-contents000': 'hh',
    '--rui-contents100': 'hh',
    '--rui-contents150': 'hh',
    '--rui-contents200': 'hh',
    '--rui-contents300': 'hh',
    '--rui-contents999': 'hh',
    '--rui-disabled': 'hh',
    '--rui-disabled-role-red': 'hh',
    '--rui-disabled-secondary': 'hh',
    '--rui-role-red': 'hh',
    '--rui-role-yellow': 'hh',
    '--rui-role-blue': 'hh',
    '--rui-role-green': 'hh',
    '--rui-bg100': 'hh',
    '--rui-bg200': 'hh',
    '--rui-bg300': 'hh',
    '--rui-bg-modal100': 'hh',
    '--rui-bg-modal200': 'hh',
    '--rui-bg-role-red': 'hh',
    '--rui-bg-secondary100': 'hh',
    '--rui-bg-highlight': 'hh',
    '--rui-bg-role-yellow': 'hh',
    '--rui-bg-role-blue': 'hh',
    '--rui-bg-role-green': 'hh',
    '--rui-white-fixed': 'hh',
    '--rui-black-fixed': 'hh',
    '--rui-divider': 'hh',
  },
};
